// <auto-generated />
using Helper.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Helper.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180213150746_ModelJednostkaHierarchia")]
    partial class ModelJednostkaHierarchia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Helper.API.Models.Jednostka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataModyfikacji");

                    b.Property<bool>("IsMain");

                    b.Property<string>("Nazwa");

                    b.Property<string>("Opis");

                    b.Property<int?>("ParentId");

                    b.Property<string>("Symbol");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Jednostki");
                });

            modelBuilder.Entity("Helper.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("InstytucjaNazwa");

                    b.Property<string>("InstytucjaRodzaj");

                    b.Property<string>("InstytucjaSymbol");

                    b.Property<DateTime>("OstatniaAktywnosc");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Telefon");

                    b.Property<string>("Username");

                    b.Property<DateTime>("Utworzony");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Helper.API.Models.Jednostka", b =>
                {
                    b.HasOne("Helper.API.Models.Jednostka", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Helper.API.Models.User", "User")
                        .WithMany("Jednostki")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
